spring:
  application:
    name: badminton-vsb



server:
  port: ${PORT:8181}

logging:
  level:
    org:
      atmosphere: warn

vaadin:
  launch-browser: false                                                            # Launch browser when starting the application.
  allowed-packages: com.vaadin,org.vaadin,com.flowingcode,de.ostfale.va
  version: '@vaadin.version@'

application:
  version: '@project.version@'

management:
  server:
    port: ${PORT:8081}
  endpoints:
    web:
      base-path: /mgmt
      exposure:
        include: info,health,prometheus
  endpoint:
    health:
      show-details: always
